### ISSUE TITLE
Contrast too low

### ISSUE THREAD

**Issue by mordae** [Dudosa3/MotherHelper#2]
Due to the use of a background gradient as well as dimmed font the contrast is not that great.
People without healthy eyesight may have trouble reading most of the text and even I cannot really read some of it.
For example:

![contrast](https://user-images.githubusercontent.com/666693/174035575-16ea597d-0c70-4373-b06d-00d50fa9f187.png)

**Comment by Dudosa3** [comment]
Ah ^^', it was my classmate who didn't finish it, but thank you so much for pointing this out : )
